window.PORTFOLIO_DATA={
  identity:{name:'Jwala Chaubey',title:'Senior Platform / SRE Engineer',location:'Pune, India',links:{website:'https://theycallmejc.github.io/',linkedin:'https://www.linkedin.com/in/jwala-chaubey/',github:'https://github.com/theycallmejc',email:'mailto:jwalachaubey@gmail.com'}},
  summary:'Eight years across cloud administration, DevOps, platform reliability, and AI/ML delivery. Builds reliable AWS platforms, Kubernetes systems, Terraform automation, observability, and AI-assisted engineering workflows.',
  metrics:[['45 min → <60 sec','Failover recovery'],['3–5 days → <30 min','Infrastructure delivery'],['45 min → <2 min','Mean time to detect'],['15+ services','Controlled delivery pipelines'],['~30%','AWS Glue ETL cost reduction']],
  experience:[
    {company:'Cognizant',client:'JPMC-CCB',role:'SRE Lead - Platform / DevOps',dates:'Jul 2025 - Jul 2026',impact:['Led SRE and production reliability initiatives for mission-critical banking applications.','Route 53 health-check failover reduced recovery from 45 min → <60 sec.','Terraform Enterprise, Git, Lambda, and EventBridge reduced provisioning from 3–5 days → <30 min across development, UAT, and production.','Built Jenkins and Spinnaker pipelines for 15+ services with approvals, validation, environment promotion, and rollback controls.','Dynatrace and Splunk across 30+ endpoints reduced MTTD from 45 min → <2 min.'],stack:['AWS ECS','Terraform Enterprise','Spinnaker','Jenkins','Dynatrace','Splunk','Route 53','ALB']},
    {company:'Cognizant',client:'JPMC-CIB',role:'Platform / DevOps Engineer - Market-data platform',dates:'Jul 2026 - Present',impact:['Developed Python services, ETL workflows, and REST APIs for a market-data platform with validation, transformation, exception handling, testing, audit logging, and production monitoring.','Worked on an AI-assisted matching service using Amazon Bedrock, LLMs, embeddings, and semantic search, containerized with Docker and deployed on ECS Fargate.','Designed and supported Terraform infrastructure across dev, test, and production using ECS Fargate, Lambda, API Gateway, IAM, S3, EventBridge, KMS, Secrets Manager, and Aurora PostgreSQL.','Supported SRE and production readiness with CloudWatch monitoring, health checks, API troubleshooting, secure service connectivity, and IAM controls.','Maintained Jenkins, Spinnaker, Git, and Terraform Enterprise delivery workflows for controlled deployments and repeatable releases.'],stack:['Python','Terraform','Docker','ECS Fargate','AWS Bedrock','Lambda','API Gateway','Aurora PostgreSQL','CloudWatch','Jenkins','Spinnaker','TFE']},
    {company:'Infosys',role:'Consultant - DevOps / AI-ML',dates:'Apr 2024 - Aug 2024',impact:['Led an AI-powered document classification service using Amazon Bedrock and Claude.','Built TypeScript Lambda integrations with retry logic, dead-letter queues, and structured CloudWatch logging.'],stack:['Amazon Bedrock','Claude','TypeScript','Lambda','CloudWatch']},
    {company:'Tata Consultancy Services',role:'AWS DevOps Engineer / Cloud Developer',dates:'Apr 2022 - Mar 2024',impact:['Provisioned production EKS clusters with ALB ingress, managed node groups, IRSA, and Container Insights.','Orchestrated Step Functions, Lambda, Glue, S3, SQS, and SES.','Reduced AWS Glue ETL costs by approximately 30% through event-driven orchestration.'],stack:['EKS','CloudFormation','Step Functions','Lambda','SQS']},
    {company:'HCL Technologies',role:'Cloud Engineer / Cloud Administrator',dates:'Aug 2019 - Apr 2022',impact:['Migrated production workloads from on-premises infrastructure to AWS using Application Migration Service.','Designed secure VPC architectures with IAM, CloudTrail, AWS Config, KMS, backup, and lifecycle controls.'],stack:['AWS MGN','VPC','IAM','CloudTrail','AWS Config']},
    {company:'Maintec Technologies',role:'Analyst',dates:'Sep 2018 - Aug 2019',impact:['Administered Splunk forwarders and index configurations for centralized logging.','Automated Windows patch management and internal workflows using PowerShell.'],stack:['Splunk','PowerShell','Windows','Active Directory']}
  ],
  skills:{'Cloud platform':['AWS','EC2','ECS','EKS','Lambda','S3','Route53','IAM','CloudWatch','Bedrock'],'Platform engineering':['Terraform Enterprise','HCL','CloudFormation','Environment-as-Code','VPC','ALB/NLB','KMS'],'Delivery systems':['Jenkins','Spinnaker','GitHub Actions','Approvals','Validation','Rollback controls'],'Reliability engineering':['Dynatrace','Splunk','CloudWatch','Failover','Incident response','Audit trails','DR replay'],'AI systems':['Python','FastAPI','RAG','AI agents','Claude','Amazon Bedrock','ChromaDB'],'Containers and context':['Docker','Kubernetes','ECS Fargate','EKS','ALB ingress','IRSA','Container Insights','GitOps']},
  projects:[
    {id:'kubesage',name:'KubeSage AI',label:'AI + Platform',description:'Self-built Kubernetes incident intelligence platform with a FastAPI backend and React/TypeScript frontend. Gathers cluster events and GitOps context, retrieves relevant evidence through ChromaDB, and surfaces likely root causes. Actively evolving as a personal ops copilot.',stack:['Python','FastAPI','React','TypeScript','ChromaDB','Kubernetes','GitOps'],link:'https://github.com/theycallmejc/kubesage-ai'},
    {id:'flowpilot',name:'FlowPilot',label:'Agent workflow',description:'Local SDLC-to-QA workflow application that turns one requirement into governed artifacts through visible, step-by-step agent handoffs: Analysis, BRD, human approval, Backlog, human approval, Test, Traceability, and QA handoff. Each agent reads the persisted artifact from the previous stage. Generation is deterministic by design and works locally without API keys.',stack:['Python','FastAPI','Agent handoffs','Human approval gates'],link:'https://github.com/theycallmejc/openai-codex#flowpilot',status:'Local MVP / deterministic workflow'},
    {id:'iac',name:'AWS Platform IaC',label:'Platform / IaC',description:'Reusable Terraform modules for ECS/EKS clusters, VPC, IAM, ALB/NLB, and Route53, with GitHub Actions gating plan/apply across three environments. Provisioning went from 4 hours to 18 minutes with zero drift incidents post-rollout.',stack:['Terraform','HCL','AWS ECS','EKS','GitHub Actions'],link:'https://github.com/theycallmejc/aws-platform-iac'},
    {id:'classifier',name:'AI Document Classifier',label:'RAG / Classification',description:'RAG pipeline on AWS Bedrock using S3 ingestion, embeddings, and Claude classification with confidence scoring. Reports 94% accuracy versus an 82% manual baseline.',stack:['TypeScript','AWS Bedrock','RAG','S3','PostgreSQL'],link:'https://github.com/theycallmejc/ai-document-classifier'},
    {id:'replay',name:'Event Store-Replay Lambda',label:'Reliability / DR',description:'Event store and replay engine for debugging production failures and enabling proactive FMEA chaos game days. Reduced MTTR from 4-6 hours to 45 minutes.',stack:['AWS Lambda','Step Functions','DynamoDB','Splunk','TypeScript'],link:'Private repo — details on request'},
    {id:'epw',name:'EPW Document Retrieval Adapter',label:'Integration / client work',description:'TypeScript adapter for legacy SOAP APIs with circuit-breaker retries, idempotent PostgreSQL writes, and Splunk audit logging. Enterprise client work is private.',stack:['TypeScript','AWS S3','SOAP','PostgreSQL','Lambda'],link:'Private repo — details on request'},
    {id:'ml',name:'ML Specialization - Notes & Projects',label:'Learning / foundations',description:"Structured notes, math derivations, and hands-on projects from Andrew Ng's Machine Learning Specialization, covering supervised learning, neural networks, and unsupervised methods.",stack:['Jupyter Notebook','Python','NumPy','scikit-learn','TensorFlow'],link:'https://github.com/theycallmejc/ML-Specialization'}
  ],
  aiContext:{status:'Local portfolio index',summary:'Grounded in verified career data. Deterministic fallback is used when no live endpoint is configured.',lenses:{'Platform Engineering':{questions:['How does AWS Platform IaC demonstrate platform engineering?','Where has Jwala used ECS and EKS?'],projects:['kubesage','flowpilot','iac'],skills:['Cloud platform','Platform engineering','Delivery systems']},'SRE / Reliability':{questions:['What production reliability problems have you solved?','How did recovery and MTTD improve?'],projects:['kubesage','replay'],skills:['Reliability engineering']},'AWS Infrastructure':{questions:['Show the strongest AWS and Terraform experience.'],projects:['iac'],skills:['Cloud platform','Platform engineering']},Kubernetes:{questions:['What has Jwala built with Kubernetes?'],projects:['kubesage'],skills:['Containers and context']},'AI Infrastructure':{questions:['What is the AI engineering experience?'],projects:['kubesage','classifier','flowpilot'],skills:['AI systems']},'DevOps Automation':{questions:['Which projects demonstrate delivery automation?'],projects:['flowpilot','iac'],skills:['Delivery systems']}}}
};
